layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by options:
    - pushed
    - stars
  limit: 6
  exclude:
    forks: true
    projects:

social_media:
  twitter: AtSerchinastico
  youtube: Serchinastico

topics:
  - name: Kotlin
    web_url: https://kotlinlang.org/
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/kotlin/kotlin.png
  - name: Swift
    web_url: https://swift.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Swift_logo.svg/667px-Swift_logo.svg.png
  - name: Clojure
    web_url: https://swift.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Clojure_logo.svg/1024px-Clojure_logo.svg.png
  - name: Testing
    web_url: https://github.com/topics/testing
    image_url: https://cdn0.iconfinder.com/data/icons/automation-testing-1/128/Set17-01-512.png
  - name: Prolog
    web_url: http://www.swi-prolog.org/
    image_url: https://avatars1.githubusercontent.com/u/6884283?s=280&v=4
  - name: Adobe After Effects
    web_url: https://www.adobe.com/products/aftereffects.html
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Adobe_After_Effects_CC_icon.svg/1200px-Adobe_After_Effects_CC_icon.svg.png
  - name: Sketch
    web_url: https://www.sketchapp.com/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Sketch_logo_frame.svg/1200px-Sketch_logo_frame.svg.png
  - name: 3D Printing
    web_url: https://www.thingiverse.com/
    image_url: http://www.feirox.com/rivu/2014/01/Thingiverse-1.png
  - name: Music
    image_url: https://musescore.org/sites/musescore.org/files/styles/width_360/public/2018-09/30alphaIcon.png?itok=N8dL65DG
  - name: Design
    image_url: https://diariodeemprendedores.com/wp-content/uploads/2014/09/domestika-curso-aprender-a-hacer-infografias-diario-de-emprendedores.png
